### ISSUE TITLE
Doesn't work on Wayland only XOrg

### ISSUE THREAD

**Issue by YusufMavzer** [carrot69/keep-presence#2]
Fedora 34 uses wayland and this one doesn't work on it

**Comment by alphamarket** [comment]
Hey there... Are you going to do something to fix this issue?

**Comment by YusufMavzer** [comment]
I'm not the one that implemented this but I can create a fix if you want

**Comment by YusufMavzer** [comment]
an update. We'll have to wait for this to be closed 
https://github.com/moses-palmer/pynput/issues/331

**Comment by carrot69** [comment]
Indeed, keep-presence uses pynput who is currently having issues as well with Wayland.
Once they fix it, we should be fine!

I don't have currently Wayland to test this for myself, but did you try running keep-presence with sudo? 
Just to know if it works that way or not.

Anyway, if someone finds a bugfix, please create a PR or tell me and I'll submit the changes.

**Comment by austinsr1** [comment]
This might not be ideal, since it requires sudo/root to move the mouse, but evemu-event does work.
Example that I found on an ask ubuntu thread:
    sudo evemu-event /dev/input/event5 --type EV_REL --code REL_X --value 50
    sudo evemu-event /dev/input/event5 --type EV_REL --code REL_Y --value 50 
    sudo evemu-event /dev/input/event5 --type EV_KEY --code BTN_RIGHT --value 1 
    sudo evemu-event /dev/input/event5 --type EV_KEY --code BTN_RIGHT --value 0

**Comment by shadeep** [comment]
I get the following error when running keep-presence with Wayland on Fedora 37.
```
Traceback (most recent call last):
  File "/snap/keep-presence/96/keep-presence.py", line 6, in <module>
    from pynput.mouse import Controller as MouseController
  File "/snap/keep-presence/96/lib/python3.6/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/snap/keep-presence/96/lib/python3.6/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/snap/keep-presence/96/lib/python3.6/site-packages/pynput/_util/__init__.py", line 82, in backend
    if resolutions else '')
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Authorization required, but no authorization protocol specified\\n\'', DisplayConnectionError(':0', b'Authorization required, but no authorization protocol specified\n'))
```

Stumbled across this while looking for a solution.  Running the following solves the authorization issue: 
`xhost si:localuser:<user-id>`

See:
https://stackoverflow.com/questions/48833451/no-protocol-specified-when-running-a-sudo-su-app-on-ubuntu-linux

**Comment by carrot69** [comment]
> an update. We'll have to wait for this to be closed [moses-palmer/pynput#331](https://github.com/moses-palmer/pynput/issues/331)

[suncoastkid](https://github.com/suncoastkid)

**Comment by carrot69** [comment]
> an update. We'll have to wait for this to be closed [moses-palmer/pynput#331](https://github.com/moses-palmer/pynput/issues/331)

@suncoastkid keep-presence uses the pynput library, we have to wait for pynput to fix the problem.
